#!/bin/bash
#########################################################################
# File Name: run_with_gpu.sh
# Author: gaoyu
# mail: gaoyu14@pku.edu.cn
# Created Time: 2018-05-11 10:15:29
#########################################################################

 CUDA_VISIBLE_DEVICES=$1 python "$2"
